### ISSUE TITLE
Generar A5D i B5D

### ISSUE THREAD

**Issue by francescpuig7** [gisce/mesures#6]
- Generar els fitxers en format `A5D` i `B5D`

![imagen](https://user-images.githubusercontent.com/19941550/108046214-a7c93300-7044-11eb-9a39-4105a95fa0c8.png)

![imagen](https://user-images.githubusercontent.com/19941550/108046135-941dcc80-7044-11eb-91f0-6d209494c137.png)

:warning: 
- c) El carácter ";" (punto y coma) delimita el final de cada campo, incluido el final de cada línea. 
- d) Los campos sin dato deberán dejarse vacíos (sin insertar ningún valor ni espacios) pero con separadores. **els R i AI, AE que toca els deixarem buits, no hi posarem 0**
- El fichero se denominará “A5D_DIS_COM_aaaammdd.v
- (3) Campo obligatorio, en Wh

**Comment by theKlanc** [comment]
https://github.com/gisce/mesures/pull/8
